### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by paulorobertodsf** [AthosFB/Exercicios-Python#1]
Cara eu fiz esse mesmo curso e no meio da minha pesquisa procurando o urllib.request, eu acabei achando uma biblioteca chamada [webbrowser](https://docs.python.org/3/library/webbrowser.html) que abre uma pagina do navegador, tenta implementar isso, caso o site estiver acessivel ele abre a pagina.

**Comment by AthosFB** [comment]
@pypaul0 Vlw man!
